---
title: "Conos analysis of pancreatic datasets"
output:
  html_document:
    df_print: paged
---

```{r,warning=FALSE, message=FALSE}
library(pagoda2)
library(conos)
library(tidyverse)
library(magrittr)
library(igraph)
library(ggpubr)
library(data.table)
library(reshape2)
library(gplots)
library(RColorBrewer)
```

## load data
```{r,warning=FALSE, message=FALSE}
pan.tiny <- readRDS(file = "/home/kvergasova/conos_analysis/data_tiny.rds")
con <- Conos$new(pan.tiny)
path <- "/home/kvergasova/conos_analysis/conos_analysis_pancreatic/"
annotation <- fread("/home/kvergasova/conos_analysis/pancreatic_annotation.tsv")
annotation <- annotation[!duplicated(annotation$cell_name),]
annotation$cell <- annotation$cell_name
```
## functions
```{r,warning=FALSE, message=FALSE}
calculateEntropy <- function(con, annotation=NULL){
  
  if (is.null(annotation)){
    groups <- conos:::parseCellGroups(con, NULL, NULL)  
  }else{
   groups <- setNames(annotation$cell_type, annotation$cell) 
  }
  
  sample.factor <- con$getDatasetPerCell()
  xt <- table(sample.factor[match(names(groups),names(sample.factor))],groups)
  xt <- xt[rowSums(xt)>0,]; xt <- xt[,colSums(xt)>0]
  n.samples <- nrow(xt)
  ne <- 1-apply(xt, 2, entropy::KL.empirical, y2=rowSums(xt), unit=c('log2')) / log2(n.samples)
  return(ne)
}

getEmbedingConos <- function(path, con, n.neig=NULL, annotation=NULL){
  ncell <- sum(sapply(con$samples, function(x) nrow(x$counts)))
  embedding <- tibble(.rows = ncell)
  plots <- list()
  j <- 1
  entropy.data <- tibble(.rows = 6)
  for (i in c(0, 0.1, 0.3, 0.5, 0.8, 1)){
      #con$misc <- NULL
      con$buildGraph(k=50, k1 = 100, k.self=5, space='PCA', ncomps=30, n.odgenes=2000, matching.method='mNN', metric='angular', score.component.variance=TRUE, verbose=TRUE,  alignment.strength = i, filt.neighbors = n.neig)
      con$findCommunities(method=leiden.community, resolution=1)
      con$embedGraph()
      plots[[j]] <- con$plotGraph(color.by='sample', mark.groups=FALSE, alpha=0.5, show.legend=TRUE)
      add.em <- tibble(x=unname(con$embeddings$largeVis[,1]), y=unname(con$embeddings$largeVis[,2]))
      colnames(add.em) <- c(str_c("x_", i),str_c("y_", i))
      embedding <- cbind(embedding, add.em)
      version <- ifelse(is.null(n.neig), "old", str_c("new_", n.neig))
      saveRDS(con$graph, str_c(path, version, "_alstr_", i, ".rds"))
      write_graph(con$graph, str_c(path, version, "_alstr_", i, ".txt"), "edgelist")
      calE <- calculateEntropy(con, annotation=NULL)
      ent <- tibble(ent = calE, cluster = names(calE))
      ent$alignment_str <- i
      entropy.data <- rbind(entropy.data, ent)
      j <- j + 1
    }
  embedding$cell <- rownames(con$embeddings$largeVis)
  fwrite(embedding, str_c(path, version, "_embedding.tsv"))
  return(list(plots=plots, emb=embedding, entropy = entropy.data))
}
getEmbedingNeighborsConos <- function(path, con, annotaion=NULL){
  pl.list <- list()
  g<-1
  embedding <- list()
  entropy.data <- tibble(.rows = 3)
  data <- tibble(.rows = sum(sapply(con$samples, function(x) nrow(x$counts)))*12)
  for (n.neig in c(0, 0.05, 0.1, 0.3, 0.5)){
   if (n.neig==0){
     res <- getEmbedingConos(path, con, n.neig = NULL, annotation)
   }else{
     res <- getEmbedingConos(path, con, n.neig, annotation)
   }  
   embedding[[g]] <- res$emb
   pl.list[[g]] <- res$plots
   data.emb <- pivot_longer(embedding[[g]], !cell, names_to = c('coord_type','alignment_str'), values_to = "coord", names_pattern = "(.)_?(.*)")
   data.emb$neig <- n.neig
   data <- rbind(data, data.emb)
   ent <- res$entropy
   ent$neig <- n.neig
   entropy.data <- rbind(entropy.data, ent)
   #fwrite(embed.df, str_c(path, "new_embedding_nneig_",n.neig,".tsv"))
   g <- g+1
  }
  fwrite(entropy.data, str_c(path, "entropy_data_pancreatic.tsv"))
  fwrite(data, str_c(path, "full_data_pancreatic.tsv"))
  return(list(plots=pl.list,emb=embedding, data=data, ent=entropy.data))
}

```

## run conos and save data
```{r, cache=FALSE, results=FALSE, warning=FALSE, comment=FALSE,message=FALSE, eval=FALSE}
conos.res <- getEmbedingNeighborsConos(path, con, annotation)
```

```{r, cache=FALSE, results=FALSE, warning=FALSE, comment=FALSE,message=FALSE}
data.file <- fread("/home/kvergasova/conos_analysis/conos_analysis_pancreatic/full_data_pancreatic.tsv")
entropy <- fread(str_c(path, "entropy_data_pancreatic.tsv"))
data <- left_join(data.file, select(annotation,!cell), by = c("cell"="cell_name"))
data <- pivot_wider(data, names_from = coord_type, values_from = coord)
data.plot <- filter(data,neig %in% c(0, 0.05), alignment_str %in% c(0,0.5,1))
```


## by protocols
```{r,  warning=FALSE, comment=FALSE,message=FALSE}
ggplot(data.plot, aes(x, y, color=protocol)) + geom_point(size=0.5, alpha=0.7) + facet_wrap(neig ~ alignment_str,scales='free') + theme_classic() + theme(strip.background = element_blank(), strip.text.x = element_blank(), axis.ticks = element_blank(), axis.text.x = element_blank(), axis.text.y = element_blank()) + labs(x="alignment strenght", y="percent of neighbors") +  scale_color_brewer(palette="Set1")
```


## by cell type
```{r,  warning=FALSE, comment=FALSE,message=FALSE}
ggplot(data.plot, aes(x, y, color=cell_type)) + geom_point(size=0.5, alpha=0.7) + facet_wrap(neig ~ alignment_str,scales='free') + theme_classic() + theme(strip.background = element_blank(), strip.text.x = element_blank(), axis.ticks = element_blank(), axis.text.x = element_blank(), axis.text.y = element_blank()) + labs(x="alignment strenght", y="percent of neighbors") 
```

## alpha and beta cells
```{r, warning=FALSE, comment=FALSE,message=FALSE}
data.plot.a.b <- filter(data.plot, cell_type %in% c("alpha", "beta"))
ggplot(data.plot.a.b, aes(x, y, color=cell_type)) + geom_point(size=0.5, alpha=0.7) + facet_wrap(neig ~ alignment_str,scales='free') + theme_classic() + theme(strip.background = element_blank(), strip.text.x = element_blank(), axis.ticks = element_blank(), axis.text.x = element_blank(), axis.text.y = element_blank()) + labs(x="alignment strenght", y="percent of neighbors") +  scale_color_brewer(palette="Set1")
```

```{r}
modularity.old <- tibble()
for (file in list.files(path, pattern = glob2rx("old_alstr*rds"))){
  g <- read_rds(str_c(path, file))
  batch <- tibble(cell = names(V(g)))  
  batch <- left_join(batch, annotation, by = c("cell"="cell_name"))
  modularity.old <- rbind(modularity.old,c(as.numeric(strsplit(strsplit(file, "alstr_")[[1]][[2]], ".rds")[[1]][[1]]),  modularity(g, as.numeric(as.factor(batch$protocol))),  modularity(g, as.numeric(as.factor(batch$cell_type)))))
}
colnames(modularity.old) <- c("Alignment_str", "modularity_by_protocol", "modularity_by_cellType")
modularity.old <- modularity.old[order(modularity.old$Alignment_str),]
modularity.new <- tibble()
for (file in list.files(path, pattern = glob2rx("new*rds"))){
  g <- read_rds(str_c(path, file))
  batch <- tibble(cell = names(V(g)))  
  batch <- left_join(batch, annotation, by = c("cell"="cell_name"))
  nneigh <- as.numeric(strsplit(strsplit(file, ".rds")[[1]][[1]], "_")[[1]][[2]])
  alstr <- as.numeric(strsplit(strsplit(file, ".rds")[[1]][[1]], "_")[[1]][[4]])
  modularity.new <- rbind(modularity.new,c(nneigh,  alstr,  modularity(g, as.numeric(as.factor(batch$protocol))),  modularity(g, as.numeric(as.factor(batch$cell_type)))))
}
colnames(modularity.new) <- c("N_neighb","Alignment_str", "modularity_by_protocol", "modularity_by_cellType")

```


## modularity by cell type
```{r,cache=FALSE,  warning=FALSE, comment=FALSE,message=FALSE}
Colors=brewer.pal(11,"Spectral")
Colors=colorRampPalette(Colors)(200)

df.long <- dcast(modularity.new, N_neighb~Alignment_str, value.var = "modularity_by_cellType")
df.long <- rbind(df.long, c(0, modularity.old$modularity_by_cellType))
df.long <- df.long[order(df.long$N_neighb),]
mm <- as.matrix(df.long[,-1])
rownames(mm) <- df.long[,1]
mm <- round(mm, 3)

heatmap.2(x = mm, Rowv = FALSE, Colv = FALSE,
          cellnote = mm, notecol = "black", notecex = 1, trace = "none",
           col=Colors, margins = c(7, 11), srtCol=0, xlab = 'Alignment str.', ylab = "neighbors", density.info="none")
```


## modularity by batch
```{r, cache=FALSE,  warning=FALSE, comment=FALSE,message=FALSE}
df.prot <- dcast(modularity.new, N_neighb~Alignment_str, value.var = "modularity_by_protocol")
df.prot <- rbind(df.prot, c(0, modularity.old$modularity_by_protocol))
df.prot <- df.prot[order(df.prot$N_neighb),]
mm1 <- as.matrix(df.prot[,-1])
rownames(mm1) <- df.prot[,1]
mm1 <- round(mm1, 3)


heatmap.2(x = mm1, Rowv = FALSE, Colv = FALSE,
          cellnote = mm1, notecol = "black", notecex = 1, trace = "none",
           col=Colors, margins = c(7, 11), srtCol=0, xlab = 'Alignment str.', ylab = "neighbors", density.info="none")

```


## entropy
```{r, fig.width=10, fig.height=4}
entropy %>% filter(neig %in% c(0,0.05,0.5), alignment_str %in% c(0,0.5,1)) %>% ggplot(aes(x = cluster, y = ent, color = as.factor(alignment_str))) + geom_line() + geom_point() + facet_wrap(~neig, nrow = 1) + theme_classic()  + labs(x="cluster", y="entropy") +  scale_color_brewer(palette="Set1")
```

