---
title: "R Notebook"
output: html_notebook
---

#создание симулированного датасета

```{r}

library(splatter)
sample_group_props <- function(sim, batch_ncells, batch_props) {

    # Get the cell metadata
    col_data <- as.data.frame(colData(sim))

    # Get the current counts of each group in each batch
    sim_batch_group_count <- table(col_data$Batch, col_data$Group)

    # Get the final number of each group in each batch
    batch_group_ncells <- lapply(seq_along(batch_ncells), function(idx) {
        batch_ncells[idx] * batch_props[[idx]]
    })

    # Check that we aren't trying to get more cells than we have
    lapply(seq_along(batch_group_ncells), function(idx) {
        if (any(batch_group_ncells[[idx]] > sim_batch_group_count[idx, ])) {
            stop("Not enough cells for these proportions in batch ", idx)
        }
    })

    # Downsample cells
    selected <- lapply(seq_along(batch_group_ncells), function(batch) {
        group_cells <- batch_group_ncells[[batch]]
        is_batch <- col_data$Batch == paste0("Batch", batch)
        batch_groups <- col_data$Group[is_batch]
        # Downsample batch
        selected_batch <- sapply(seq_along(group_cells), function(group) {
            is_group <- batch_groups == paste0("Group", group)
            sample(col_data$Cell[is_batch][is_group], group_cells[group])
        })
        unlist(selected_batch)
    })
    selected <- as.character(unlist(selected))

    # Subset SingleCellExperiment
    sim[, selected]
}
```

```{r}
base_params <- newSplatParams()

sim2_params <- setParams(
    base_params,
    lib.loc        = 12,
    # Two batches with 1000 cells each. Needs to be more than we want in the
    # final simulation.
    batchCells     = c(2000, 2000, 2000, 2000) * 10,
    batch.facLoc   = c(0.20, 0.25, 0.22, 0.28),
    batch.facScale = c(0.10, 0.08, 0.12, 0.10),
    # Groups with equal probabilities
    group.prob     = rep(1, 4) / 4,
    # Differential expression by group
    de.prob        = c(0.10, 0.12, 0.08, 0.20),
    de.facLoc      = c(0.10, 0.08, 0.12, 0.18),
    de.facScale    = c(0.40, 0.30, 0.45, 0.48),
    # Seed
    seed           = 1
)

# Simulate the full dataset that we will downsample
sim2_full <- splatSimulateGroups(sim2_params)

# Number of cells in each batch in the final simulation
batch_ncells <- c(1000, 1000, 1000, 1000) * 10

# Proportions in each group in each batch that we want. Should sum to 1.
batch_props <- list(
    c(0.35, 0.37, 0.15, 0.13),
    c(0.25, 0.1, 0.50, 0.15),
    c(0.2, 0.2, 0.13, 0.47),
    c(0.3, 0.5, 0.2, 0.2)
)

# Downsample cells in our simulation
message("Downsampling cells...")
sim2 <- sample_group_props(sim2_full, batch_ncells, batch_props)

# Set proportion of counts for each batch (relative library size)
batch_count_props <- c(
    Batch1 = 1.00,
    Batch2 = 0.70,
    Batch3 = 0.60,
    Batch4 = 0.30
)
cell_count_props <- batch_count_props[colData(sim2)$Batch]

add_subbatches <- function(sim, subbatch_props) {
    message("Adding subbatches...")
    # browser()
    params <- metadata(sim)$Params
    n_batches <- getParam(params, "nBatches")

    if (!all(sapply(subbatch_props, sum) == 1)) {
        stop("Not all subbatch props sum to 1")
    }

    colData(sim)$SubBatch <- NA

    for (batch_idx in seq_len(n_batches)) {

        message("Processing Batch ", batch_idx, "...")

        batch <- paste0("Batch", batch_idx)
        is_batch <- colData(sim)$Batch == batch
        batch_size <- sum(is_batch)

        subbatches <- BBmisc::chunk(colnames(sim)[is_batch],
                                    props = subbatch_props[[batch_idx]],
                                    shuffle = FALSE)

        for (subbatch_idx in seq_along(subbatches)) {

            message("Adding SubBatch ", subbatch_idx, "...")

            subbatch_cells <- subbatches[[subbatch_idx]]

            noise_sim <- splatSimulate(
                batchCells = length(subbatch_cells),
                lib.loc    = 8.00,
                lib.scale  = 0.50,
                verbose    = FALSE,
                seed       = batch_idx * subbatch_idx
            )

           counts(sim)[, subbatch_cells] <- counts(sim)[, subbatch_cells] + as.matrix(counts(noise_sim))
            colData(sim)[subbatch_cells, "Sub"] <- paste0("Sub", subbatch_idx)
            colData(sim)[subbatch_cells, "SubBatch"] <- paste0(batch,
                                                               "Sub", subbatch_idx)
        }
    }

    return(sim)
}

subbatch_props <- list(
    c(0.25, 0.25, 0.25, 0.25),
    c(0.30, 0.30, 0.20, 0.20),
    c(0.40, 0.25, 0.25, 0.10),
    c(0.35, 0.35, 0.15, 0.15)
)

sim2 <- add_subbatches(sim2, subbatch_props)

# Downsample counts
message("Downsampling counts...")
counts(sim2) <- DropletUtils::downsampleMatrix(counts(sim2), cell_count_props,
                                               bycol = TRUE)

message("Calculating QC...")
sim2 <- scater::addPerCellQC(sim2)

# Reorder by SubBatch
subbatch_order <- order(colData(sim2)$SubBatch)
sim2 <- sim2[, subbatch_order]

discard <- lapply(unique(colData(sim2)$SubBatch), function(subbatch) {
    in_batch <- colData(sim2)$SubBatch == subbatch
    scater::quickPerCellQC(colData(sim2)[in_batch, ], nmads = 2)$discard
})
discard <- unlist(discard)
colData(sim2)$Discard <- discard

message("Filtering cells...")
sim2_qc <- sim2[, !discard]
message("Filtering genes...")
sim2_qc <- scater::addPerFeatureQC(sim2_qc)
is_exprs <- rowData(sim2_qc)$detected >= 0.01
sim2_qc <- sim2_qc[is_exprs, ]

message("Normalising...")
sim2 <- scater::logNormCounts(sim2)
sim2_qc <- scater::logNormCounts(sim2_qc)
message("Embedding...")
sim2 <- scater::runTSNE(sim2)
sim2_qc <- scater::runTSNE(sim2_qc)

message("Saving QC plots..")
fs::dir_create("qc_plots/sim2")

scater::plotTSNE(sim2, colour_by = "Batch")
ggplot2::ggsave("qc_plots/sim2/tsne-batch.png")
scater::plotTSNE(sim2, colour_by = "SubBatch")
ggplot2::ggsave("qc_plots/sim2/tsne-subbatch.png")
scater::plotTSNE(sim2, colour_by = "Group")
ggplot2::ggsave("qc_plots/sim2/tsne-group.png")
scater::plotTSNE(sim2, colour_by = "total")
ggplot2::ggsave("qc_plots/sim2/tsne-total.png")
scater::plotTSNE(sim2_qc, colour_by = "Batch")
ggplot2::ggsave("qc_plots/sim2/tsne-batch-qc.png")
scater::plotTSNE(sim2_qc, colour_by = "SubBatch", shape_by = "Batch")
ggplot2::ggsave("qc_plots/sim2/tsne-subbatch-qc.png")
scater::plotTSNE(sim2_qc, colour_by = "Group")
ggplot2::ggsave("qc_plots/sim2/tsne-group-qc.png")
scater::plotTSNE(sim2_qc, colour_by = "total")
ggplot2::ggsave("qc_plots/sim2/tsne-total-qc.png")
scater::plotTSNE(sim2, colour_by = "Discard")
ggplot2::ggsave("qc_plots/sim2/tsne-filt.png")
scater::plotColData(sim2, "sum", "detected", colour_by = "Discard",
                    other_fields = c("Batch", "Sub")) +
    ggplot2::scale_x_log10() +
    ggplot2::scale_y_log10() +
    ggplot2::facet_grid(Batch ~ Sub, scales = "free")
ggplot2::ggsave("qc_plots/sim2/filtering.png")

message("Converting to AnnData...")
anndata <- reticulate::import("anndata")
sim2_adata <- anndata$AnnData(
    X = t(counts(sim2)),
    obs = data.frame(colData(sim2)),
    var = data.frame(rowData(sim2))
)
sim2_qc_adata <- anndata$AnnData(
    X = t(counts(sim2_qc)),
    obs = data.frame(colData(sim2_qc)),
    var = data.frame(rowData(sim2_qc))
)

message("Saving simulation...")
fs::dir_create("simulations")
# Remove intermediate matrices to reduce file size
assays(sim2) <- assays(sim2)[assayNames(sim2) == "counts"]
assays(sim2_qc) <- assays(sim2_qc)[assayNames(sim2_qc) == "counts"]
saveRDS(sim2, "/home/kvergasova/conos_analysis/sim2.Rds")
saveRDS(sim2_qc, "simulations/sim2_qc.Rds")
sim2_adata$write(filename = "simulations/sim2.h5ad")
sim2_qc_adata$write(filename = "simulations/sim2_qc.h5ad")
```


#Batch 1. 
Group1 Group2 Group3 Group4 
 11000  11700   9800   9500 
 
```{r}
sim2 <-readRDS("/home/kvergasova/conos_analysis/mouse_brain/simulations/sim2.Rds")
mat <- counts(sim2)
# cells <- make.unique(rep("cell", times = ncol(mat)+1), sep = "_")
# cells <- cells[-1]
annotation <- tibble(cell=sim2$Cell, protocol = sim2$Batch, cellType = sim2$Group )
fwrite(annotation, "/home/kvergasova/conos_analysis/mouse_brain/simulations/annotation_sim2.tsv")
```


```{r}
cm <- counts(sim2)[, sim2$Batch == "Batch1"]
cm <- cm[,runif(ncol(cm), min=0, max=1) > 0.7]

par(mfrow=c(1,2), mar = c(3.5,3.5,2.0,0.5), mgp = c(2,0.65,0), cex = 1.0)
hist(log10(colSums(cm)+1), main='molecules per cell', col='cornsilk', xlab='log10(molecules per cell)')
hist(log10(rowSums(cm)+1), main='molecules per gene', col='cornsilk', xlab='log10(molecules per gene])')

cm <- as.matrix(cm)
#counts <- gene.vs.molecule.cell.filter(cm, min.cell.size=100)
counts <- cm
hist(log10(rowSums(counts)+1), main='Molecules per gene', xlab='molecules (log10)', col='cornsilk')
abline(v=1, lty=2, col=2)
counts <- counts[rowSums(counts)>=10, ]
dim(counts)
rownames(counts) <- make.unique(rownames(counts))
r1 <- Pagoda2$new(counts,log.scale=TRUE, n.cores=2)

r1$adjustVariance(plot=TRUE, gam.k=10)
r1$calculatePcaReduction(nPcs=50, n.odgenes=3e3)
r1$makeKnnGraph(k=40, type='PCA', center=TRUE, distance='cosine')
r1$getKnnClusters(method=infomap.community, type='PCA')
M <- 30
r1$getEmbedding(type='PCA', embeddingType = 'largeVis', M=M, perplexity=30, gamma=1/M, alpha=1)
r1$plotEmbedding(type='PCA', show.legend=FALSE, mark.clusters=TRUE, min.group.size=50, shuffle.colors=FALSE, mark.cluster.cex=1, alpha=0.1, main='clusters (largeVis)')
#r$getEmbedding(type='PCA', embeddingType='tSNE', perplexity=50,verbose=FALSE)
#r$plotEmbedding(type='PCA', embeddingType='tSNE', show.legend=FALSE, mark.clusters=TRUE, min.group.size=1, shuffle.colors=FALSE, mark.cluster.cex=1, alpha=0.1, main='clusters (tSNE)')
r1$getKnnClusters(method=multilevel.community, type='PCA', name='multilevel')
```


Group1 Group2 Group3 Group4 
 11000  11700   9800   9500 
 
 Group1 Group2 Group3 Group4 
 110  11700   9800   9500 
```{r}
cm <- counts(sim2)[, sim2$Batch == "Batch2"]
cm <- cm[,runif(ncol(cm), min=0, max=1) > 0.5]
# id1 <- cm[,colnames(cm) == 'Group1'][runif(sum(sim2$Group == 'Group1'), min=0, max=1) > 0.99]]
# cm <- which(sim2$Group == 'Group2')[runif(sum(sim2$Group == 'Group1'), min=0, max=1) > 0.99]

par(mfrow=c(1,2), mar = c(3.5,3.5,2.0,0.5), mgp = c(2,0.65,0), cex = 1.0)



hist(log10(colSums(cm)+1), main='molecules per cell', col='cornsilk', xlab='log10(molecules per cell)')
hist(log10(rowSums(cm)+1), main='molecules per gene', col='cornsilk', xlab='log10(molecules per gene])')

cm <- as.matrix(cm)
#counts <- gene.vs.molecule.cell.filter(cm, min.cell.size=100)
counts <- cm
hist(log10(rowSums(counts)+1), main='Molecules per gene', xlab='molecules (log10)', col='cornsilk')
abline(v=1, lty=2, col=2)
counts <- counts[rowSums(counts)>=10, ]
dim(counts)
rownames(counts) <- make.unique(rownames(counts))
r2 <- Pagoda2$new(counts,log.scale=TRUE, n.cores=2)

r2$adjustVariance(plot=TRUE, gam.k=10)
r2$calculatePcaReduction(nPcs=50, n.odgenes=3e3)
r2$makeKnnGraph(k=40, type='PCA', center=TRUE, distance='cosine')
r2$getKnnClusters(method=infomap.community, type='PCA')
M <- 30
r2$getEmbedding(type='PCA', embeddingType = 'largeVis', M=M, perplexity=30, gamma=1/M, alpha=1)
r2$plotEmbedding(type='PCA', show.legend=FALSE, mark.clusters=TRUE, min.group.size=50, shuffle.colors=FALSE, mark.cluster.cex=1, alpha=0.1, main='clusters (largeVis)')
#r$getEmbedding(type='PCA', embeddingType='tSNE', perplexity=50,verbose=FALSE)
#r$plotEmbedding(type='PCA', embeddingType='tSNE', show.legend=FALSE, mark.clusters=TRUE, min.group.size=1, shuffle.colors=FALSE, mark.cluster.cex=1, alpha=0.1, main='clusters (tSNE)')
r2$getKnnClusters(method=multilevel.community, type='PCA', name='multilevel')
```

```{r}
cm <- counts(sim2)[, sim2$Batch == "Batch3"]
cm <- cm[,runif(ncol(cm), min=0, max=1) > 0.9]
par(mfrow=c(1,2), mar = c(3.5,3.5,2.0,0.5), mgp = c(2,0.65,0), cex = 1.0)
hist(log10(colSums(cm)+1), main='molecules per cell', col='cornsilk', xlab='log10(molecules per cell)')
hist(log10(rowSums(cm)+1), main='molecules per gene', col='cornsilk', xlab='log10(molecules per gene])')

cm <- as.matrix(cm)
#counts <- gene.vs.molecule.cell.filter(cm, min.cell.size=100)
counts <- cm
hist(log10(rowSums(counts)+1), main='Molecules per gene', xlab='molecules (log10)', col='cornsilk')
abline(v=1, lty=2, col=2)
counts <- counts[rowSums(counts)>=10, ]
dim(counts)
rownames(counts) <- make.unique(rownames(counts))
r3 <- Pagoda2$new(counts,log.scale=TRUE, n.cores=2)

r3$adjustVariance(plot=TRUE, gam.k=10)
r3$calculatePcaReduction(nPcs=50, n.odgenes=3e3)
r3$makeKnnGraph(k=40, type='PCA', center=TRUE, distance='cosine')
r3$getKnnClusters(method=infomap.community, type='PCA')
M <- 30
r3$getEmbedding(type='PCA', embeddingType = 'largeVis', M=M, perplexity=30, gamma=1/M, alpha=1)
r3$plotEmbedding(type='PCA', show.legend=FALSE, mark.clusters=TRUE, min.group.size=50, shuffle.colors=FALSE, mark.cluster.cex=1, alpha=0.1, main='clusters (largeVis)')
#r$getEmbedding(type='PCA', embeddingType='tSNE', perplexity=50,verbose=FALSE)
#r$plotEmbedding(type='PCA', embeddingType='tSNE', show.legend=FALSE, mark.clusters=TRUE, min.group.size=1, shuffle.colors=FALSE, mark.cluster.cex=1, alpha=0.1, main='clusters (tSNE)')
r3$getKnnClusters(method=multilevel.community, type='PCA', name='multilevel')
```

```{r}
cm <- counts(sim2)[, sim2$Batch == "Batch4"]
cm <- cm[,runif(ncol(cm), min=0, max=1) > 0.6]
par(mfrow=c(1,2), mar = c(3.5,3.5,2.0,0.5), mgp = c(2,0.65,0), cex = 1.0)
hist(log10(colSums(cm)+1), main='molecules per cell', col='cornsilk', xlab='log10(molecules per cell)')
hist(log10(rowSums(cm)+1), main='molecules per gene', col='cornsilk', xlab='log10(molecules per gene])')

cm <- as.matrix(cm)
#counts <- gene.vs.molecule.cell.filter(cm, min.cell.size=100)
counts <- cm
hist(log10(rowSums(counts)+1), main='Molecules per gene', xlab='molecules (log10)', col='cornsilk')
abline(v=1, lty=2, col=2)
counts <- counts[rowSums(counts)>=10, ]
dim(counts)
rownames(counts) <- make.unique(rownames(counts))
r4 <- Pagoda2$new(counts,log.scale=TRUE, n.cores=2)

r4$adjustVariance(plot=TRUE, gam.k=10)
r4$calculatePcaReduction(nPcs=50, n.odgenes=3e3)
r4$makeKnnGraph(k=40, type='PCA', center=TRUE, distance='cosine')
r4$getKnnClusters(method=infomap.community, type='PCA')
M <- 30
r4$getEmbedding(type='PCA', embeddingType = 'largeVis', M=M, perplexity=30, gamma=1/M, alpha=1)
r4$plotEmbedding(type='PCA', show.legend=FALSE, mark.clusters=TRUE, min.group.size=50, shuffle.colors=FALSE, mark.cluster.cex=1, alpha=0.1, main='clusters (largeVis)')
#r$getEmbedding(type='PCA', embeddingType='tSNE', perplexity=50,verbose=FALSE)
#r$plotEmbedding(type='PCA', embeddingType='tSNE', show.legend=FALSE, mark.clusters=TRUE, min.group.size=1, shuffle.colors=FALSE, mark.cluster.cex=1, alpha=0.1, main='clusters (tSNE)')
r4$getKnnClusters(method=multilevel.community, type='PCA', name='multilevel')
```


```{r}
panel <- list("batch1" = r1, "batch2" = r2, "batch3" = r3, "batch4" = r4)
saveRDS(panel, "/home/kvergasova/conos_analysis/mouse_brain/simulations/panel_sim2.rds")
```

```{r}
conS <- Conos$new(panel, n.cores=4)

findCells <- function(sample, k = 0.05){
  #k <- dim(sample$reductions$PCA)[1]*per
  n.cells <-  round(dim(sample$reductions$PCA)[1]*k)
  mat <- conos:::getNeighborMatrix(p1 = sample$reductions$PCA, p2=NULL, k = n.cells, matching = "NN")
  colnames(mat) <- rownames(sample$reductions$PCA)
  rownames(mat) <- rownames(sample$reductions$PCA)
  num.elements <- colSums(mat!=0)
  cell.distance <- mat@x
  list.cell <- list()
  j <- 1
  for (i in 1:dim(mat)[1]){
    sep <-num.elements[i]  
    cells <- setNames(cell.distance[j:(sep+j-1)], colnames(mat)[mat@i[j:(sep+j-1)]+1])
    cells <- cells[order(cells, decreasing = T)[1:n.cells]]
    list.cell <- c(list.cell, list(cells))
    j <- j + sep
  }
  names(list.cell) <- colnames(mat)
  #sample$misc <- list.cell
  return(list.cell)
}

conS$misc <- NULL
#con$misc$neighborfilter <- lapply(con$samples, function(x) findCells(x, 0.5))
#con$misc$add.cells <- TRUE
#con$misc$add.cells.times <- 1
# cono.b$mispan.tiny <- readRDS(file = "data_tiny.rds")
#c <- lapply(cono.b$samples, function(x) findCells(x, 0.1))
#cell.names <- lapply(self$samples,getCellNames)
#undebug(cono.t$buildGraph)
#con$misc <- NULL

#conS$misc$neighborfilter <- lapply(conS$samples, function(x) findCells(x, 0.15))
#conS$misc$add.cells <- FALSE
pl.sim.old.sam <- list()
pl.sim.old.group <- list()
j <- 1
embeg.sim2.old <- tibble(cell=rownames(conS$embeddings$largeVis))
 for (i in c(0, 0.1, 0.3, 0.5, 0.8, 1)){
      
  conS$buildGraph(k=50, k1 = 100, k.self=5, space='PCA', ncomps=30, n.odgenes=2000, matching.method='mNN', metric='angular', score.component.variance=TRUE, verbose=TRUE,  alignment.strength = i)
  
  conS$findCommunities(method=leiden.community, resolution=1)
  conS$embedGraph()
  #cono.tiny$plotGraph(alpha=0.1)
  df <- tibble(conS$embeddings$largeVis[,1], conS$embeddings$largeVis[,2])
  colnames(df) <- c(str_c("x_", i), str_c("y_", i))
  embeg.sim2.old <- cbind(embeg.sim2.old, df)
  ann.sim <- setNames(sim2$Group, sim2$Cell)
  pl.sim.old.group[[j]]<-conS$plotGraph(group = ann.sim , mark.groups=FALSE, alpha=0.1, show.legend=TRUE)
  pl.sim.old.sam[[j]] <- conS$plotGraph(color.by='sample',mark.groups=FALSE, alpha=0.1, show.legend=TRUE)
  j <- j +1
 }

head(embeg.sim2.old)
library(data.table)
fwrite(embeg.sim2.old, "simulations/embeddings_simulation2.csv")

pl.sim.group <- list()
pl.sim.sam <- list()
embeg.sim2 <- list()
for (n.neig in c(0.05, 0.1, 0.3, 0.5)){
  #j <- 1
  
  embeg.sim2.df <- tibble(cell=rownames(conS$embeddings$largeVis))
  conS$misc$neighborfilter <- lapply(conS$samples, function(x) findCells(x, n.neig))
  conS$misc$add.cells <- FALSE
  j <- 1
  for (i in c(0, 0.1, 0.3, 0.5, 0.8, 1)){
  conS$buildGraph(k=50, k1 = 100, k.self=5, space='PCA', ncomps=30, n.odgenes=2000, matching.method='mNN', metric='angular', score.component.variance=TRUE, verbose=TRUE,  alignment.strength = i)
  
  conS$findCommunities(method=leiden.community, resolution=1)
  conS$embedGraph()
  #cono.tiny$plotGraph(alpha=0.1)
  df <- tibble(conS$embeddings$largeVis[,1], conS$embeddings$largeVis[,2])
  colnames(df) <- c(str_c("x_", i), str_c("y_", i))
  embeg.sim2.df <- cbind(embeg.sim2.df, df)
  ann.sim <- setNames(sim2$Group, sim2$Cell)
  pl.sim.group[[str_c("n.neig_", n.neig)]][[j]]<-conS$plotGraph(group = ann.sim , mark.groups=FALSE, alpha=0.1, show.legend=TRUE)
  pl.sim.sam[[str_c("n.neig_", n.neig)]][[j]] <- conS$plotGraph(color.by='sample',mark.groups=FALSE, alpha=0.1, show.legend=TRUE)
  j <- j +1
  }
  embeg.sim2[[str_c("n.neig_", n.neig)]] <- embeg.sim2.df
}
      
saveRDS(embeg.sim2, "embedding_sim2_al_neigh.rds")      

```
```{r}
ggarrange(pl.sim.old.sam[[1]]+  theme(legend.position = "none"), pl.sim.old.sam[[2]]+  theme(legend.position = "none"), pl.sim.old.sam[[3]]+  theme(legend.position = "none"), pl.sim.old.sam[[4]]+  theme(legend.position = "none"), pl.sim.old.sam[[5]]+  theme(legend.position = "none"),pl.sim.old.sam[[6]]+  theme(legend.position = "none"),
        pl.sim.sam[[1]][[1]] + theme(legend.position = "none"),
        pl.sim.sam[[1]][[2]] + theme(legend.position = "none"),
        pl.sim.sam[[1]][[3]] + theme(legend.position = "none"),
        pl.sim.sam[[1]][[4]] + theme(legend.position = "none"),
        pl.sim.sam[[1]][[5]] + theme(legend.position = "none"),
        pl.sim.sam[[1]][[6]] + theme(legend.position = "none"),
        pl.sim.sam[[2]][[1]] + theme(legend.position = "none"),
        pl.sim.sam[[2]][[2]] + theme(legend.position = "none"),
        pl.sim.sam[[2]][[3]] + theme(legend.position = "none"),
        pl.sim.sam[[2]][[4]] + theme(legend.position = "none"),
        pl.sim.sam[[2]][[5]] + theme(legend.position = "none"),
        pl.sim.sam[[2]][[6]] + theme(legend.position = "none"),
        pl.sim.sam[[3]][[1]] + theme(legend.position = "none"),
        pl.sim.sam[[3]][[2]] + theme(legend.position = "none"),
        pl.sim.sam[[3]][[3]] + theme(legend.position = "none"),
        pl.sim.sam[[3]][[4]] + theme(legend.position = "none"),
        pl.sim.sam[[3]][[5]] + theme(legend.position = "none"),
        pl.sim.sam[[3]][[6]] + theme(legend.position = "none"),
        pl.sim.sam[[4]][[1]] + theme(legend.position = "none"),
        pl.sim.sam[[4]][[2]] + theme(legend.position = "none"),
        pl.sim.sam[[4]][[3]] + theme(legend.position = "none"),
        pl.sim.sam[[4]][[4]] + theme(legend.position = "none"),
        pl.sim.sam[[4]][[5]] + theme(legend.position = "none"),
        pl.sim.sam[[4]][[6]] + theme(legend.position = "none"),
          ncol = 6, nrow = 5)
```

```{r}
ggarrange(pl.sim.old.group[[1]]+  theme(legend.position = "none"), pl.sim.old.group[[2]]+  theme(legend.position = "none"), pl.sim.old.group[[3]]+  theme(legend.position = "none"), pl.sim.old.group[[4]]+  theme(legend.position = "none"), pl.sim.old.group[[5]]+  theme(legend.position = "none"),pl.sim.old.group[[6]]+  theme(legend.position = "none"),
        pl.sim.group[[1]][[1]] + theme(legend.position = "none"),
        pl.sim.group[[1]][[2]] + theme(legend.position = "none"),
        pl.sim.group[[1]][[3]] + theme(legend.position = "none"),
        pl.sim.group[[1]][[4]] + theme(legend.position = "none"),
        pl.sim.group[[1]][[5]] + theme(legend.position = "none"),
        pl.sim.group[[1]][[6]] + theme(legend.position = "none"),
        pl.sim.group[[2]][[1]] + theme(legend.position = "none"),
        pl.sim.group[[2]][[2]] + theme(legend.position = "none"),
        pl.sim.group[[2]][[3]] + theme(legend.position = "none"),
        pl.sim.group[[2]][[4]] + theme(legend.position = "none"),
        pl.sim.group[[2]][[5]] + theme(legend.position = "none"),
        pl.sim.group[[2]][[6]] + theme(legend.position = "none"),
        pl.sim.group[[3]][[1]] + theme(legend.position = "none"),
        pl.sim.group[[3]][[2]] + theme(legend.position = "none"),
        pl.sim.group[[3]][[3]] + theme(legend.position = "none"),
        pl.sim.group[[3]][[4]] + theme(legend.position = "none"),
        pl.sim.group[[3]][[5]] + theme(legend.position = "none"),
        pl.sim.group[[3]][[6]] + theme(legend.position = "none"),
        pl.sim.group[[4]][[1]] + theme(legend.position = "none"),
        pl.sim.group[[4]][[2]] + theme(legend.position = "none"),
        pl.sim.group[[4]][[3]] + theme(legend.position = "none"),
        pl.sim.group[[4]][[4]] + theme(legend.position = "none"),
        pl.sim.group[[4]][[5]] + theme(legend.position = "none"),
        pl.sim.group[[4]][[6]] + theme(legend.position = "none"),
          ncol = 6, nrow = 5)
```

```{r}
conS$misc$neighborfilter <- lapply(conS$samples, function(x) findCells(x, 0.15))
conS$misc$add.cells <- FALSE
conS$buildGraph(k=50, k1 = 100, k.self=5, space='PCA', ncomps=30, n.odgenes=2000, matching.method='mNN', metric='angular', score.component.variance=TRUE, verbose=TRUE,  alignment.strength = 0.5)
  
conS$findCommunities(method=leiden.community, resolution=1)
conS$embedGraph()

ann.sim <- setNames(sim2$Group, sim2$Cell)
 conS$plotGraph(group = ann.sim , mark.groups=FALSE, alpha=0.1, show.legend=TRUE)
conS$plotGraph(color.by='sample',mark.groups=FALSE, alpha=0.1, show.legend=TRUE)
  
```

